### ISSUE TITLE
How to handle popup dialog?

### ISSUE THREAD

**Issue by fluxnewbie** [lgvalle/android-flux-todo-app#10]
Hi, 
I am new start of Flux. 
Step : 
1) Started a new activity.
2) Display a popup box for the message from previous activity
e.g. Type username press login, go to Home page display the popup.

Questions:
1) Is trigger the popup from Activity directly? 
OR 
Activity (passing message & activity [Home Activity]) => ActionCreator => Dispatcher => Store (invoke activity function to display popup with the message passing in from first step) => Activity (same activity [Home Activity])?

2) Should keep the message in Store instead of intent?

**Comment by lgvalle** [comment]
The message is an UI representation of your app internal state. This internal state should be saved in your Stores and then is Activity (UI) responsibility to check Stores and update views accordingly.
