### ISSUE TITLE
Issue with Single Dispatcher

### ISSUE THREAD

**Issue by omamapk** [lgvalle/android-flux-todo-app#13]
#Hi lgvalle,

Thankyou for the code implementation, that help me understand flux architecture really well.

I have implemented your architecture in my code. But at one point came I had to break the rule of single dispatcher which is the core of flux architecture.

While there are some actions that are being propagate through UI, I have a background service that hits api server every 30 seconds. As soon as one store working on UI event, another store change event from background service register by dispatcher that nullifies my last change event call and post a null object to OTTO event bus hence view controller in UI never informed that the task is finished. To resolve this problem I had to create another dispatcher to keep background service work on separate thread thus ended up in breaking the rule of single dispatcher.

Please help me to resolve my issue.
Omama Moin

**Comment by omamapk** [comment]
Sorry i was passing null object as a event. Issue resolved :)

**Comment by lgvalle** [comment]
Glad to hear is fixed!
