### ISSUE TITLE
can u provide a template with the network requset

### ISSUE THREAD

**Issue by JiangDaYa0** [lgvalle/android-flux-todo-app#4]

**Comment by juefei** [comment]
I want to talk about APIAdapter(network logic or DB) and TodoStore, for example:  when I receive a view event to create a todo data in TodoStore, and also want to save it into DB,  how can i do?  are viewAction for TodoStore and modelAction for APIAdapter appropriate？

**Comment by lgvalle** [comment]
@JiangDaYa0 @juefei 
What I do for network requests is roughly:

(_Having in mind that all actions are triggered from the UI_)
- `ActionsCreator` contains a class `Mediator` which does network requests.
- Any action that needs a network request (fetch notes for example) dispatch a regular Action but also makes a call to this `Mediator` class.
- `Mediator` will make the network call and dispatch another Action with the results.
- Is up to the Stores to listen to this Server Response Actions and do something with them
