### ISSUE TITLE
Breaking unidirectional data flow principle ??

### ISSUE THREAD

**Issue by kevinlg** [lgvalle/android-flux-todo-app#6]
Thanks for this very good example it helped me a lot to get started with the flux architecture. And I am implementing it in my application.

I am wondering, if by having a reference to the Dispatcher in the Store and emitting the Store changes event with this Dispatcher you are not breaking the unidirectional principal ?

I think that by using the dispatcher to emit the the event the event goes back from store to the dispatcher. It is where I think there is a problem in your implementation.

If the store was able to emit changes directly to the view then I think the flow will be respected.

Let me know what you think about it

Kevin,

**Comment by lgvalle** [comment]
Hi @kevinlg, thanks for your comments. It's a very good question.

Unidirectional data flow is a key principle in Flux architecture and I believe one of its mayor strengths. In this example it is preserved as well. 

The `Dispatcher` is the class responsible for emitting events through the app. An Action event and a StoreChange event are conceptually different things, but the implementation is the same: events. So, that is why there is one single class, `Dispatcher`, emitting either Actions or StoreChange events. 

Unidirectional flow is still preserved. **It will be broken if we emit Actions from Stores**, but this is not happening in this example. Stores only emit StoreChange events, and Actions are only emitted from ActionCreators.

**Comment by kevinlg** [comment]
Ok, I was considering the dispatcher to be one waypoint on the flow. If you consider it as an event emitter only then your point is valid.

Thanks for answering the question. I think we can close it.
