### ISSUE TITLE
ActionCreator is too fat ?

### ISSUE THREAD

**Issue by dxungngh** [lgvalle/android-flux-todo-app#8]
![Architecture](https://raw.githubusercontent.com/lgvalle/lgvalle.github.io/master/public/images/flux-graph-complete.png)

In this architecture, `ActionCreator` file contains:
- methods when `User interact with UI`. However there are many activities, and many `interaction`.
- methods interact with API adapter.

I think there are many methods in `ActionCreator` file. 
- Do you think this file is too fat ?
- And do you have solution for this issue ?

**Comment by lopper** [comment]
You can create multiple ActionCreators. Each ActionCreator can be responsible for a particular set of actions (ie. TodoList, Account Registration).

**Comment by berial** [comment]
Each view can create a match of ActionCreatorClass. Example, LoginActionCreator ->  LoginAction -> Dispatcher -> LoginStore -> LoginActivity.

**Comment by dxungngh** [comment]
Thanks guy

**Comment by lgvalle** [comment]
That is correct: each view can create their own ActionCreator class. I would recommend to start with one single class for all your views and start dividing if it becomes too large. 
Having all actions in one single class helps identifying what the system can do very easily. This way, new developers coming to the project don't get lost tracking down where something starts.
