### ISSUE TITLE
Where do you want to put DB ?

### ISSUE THREAD

**Issue by dxungngh** [lgvalle/android-flux-todo-app#9]
In your architecture, I don't know where is right place of DB layer (ORM, datasource, sqlite, ...)
Could you explain (or draw architecture) detail of DB layer ?

**Comment by lopper** [comment]
You can put the DBLayer beneath the store. The store can add, update, and fetch from the DB.

**Comment by lgvalle** [comment]
As @lopper said persistence layer should be accessed from Stores. Is Stores responsibility to handle app status at any moment so it make sense for them to make use of a DB or any other kind of persistence mechanism to ensure this status is saved when needed

**Comment by duo2005duo** [comment]
@lgvalle 
You said stores are completely synchronous but  persistence layer is always asynchronous.So how to make stores synchronous if persisitence layer is accessed from Stores?

**Comment by duo2005duo** [comment]
@lgvalle 
And I don't quite get  why netwrok is accessed from `actioncreator` but DB is accessed from `stores`?

**Comment by duo2005duo** [comment]
@lgvalle 
What's more ,I think it's a bad idea the view pulls data from stores ,which may cause multi-thread problem .I think the stores should push data to view instead.
